export enum ActionType {
  SET_CURRENT_SONG = 'SET_SONG',
  SET_CURRENT_SONG_INFO = 'SET_SONG_INFO',
  TOGGLE_PLAYING = 'TOGGLE_PLAYING',
  TOGGLE_PLAYLIST = 'TOGGLE_PLAYLIST',
  TOGGLE_MUTE = 'TOGGLE_MUTE',
  TOGGLE_LOOP = 'TOGGLE_LOOP',
  TOGGLE_SHUFFLE = 'TOGGLE_SHUFFLE',
}